apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-bridge.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-bridge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-bridge.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-bridge.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: {{ include "kube-bridge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8171
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LOGGER_SERVICE_URL
              value: "http://logger-service:8080"
            - name: KUBE_BRIDGE_DEBUG
              value: "true"
            - name: KUBE_BRIDGE_PORT
              value: "8171"
