---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krateo-kube-bridge
  namespace: krateo-system
  labels:
    app.kubernetes.io/name: krateo-kube-bridge
    app.kubernetes.io/component: control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krateo-manager
  labels:
    app.kubernetes.io/name: krateo-manage-namespaces
    app.kubernetes.io/component: control-plane
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - get
      - delete
      - list

  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"

  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - "*"

  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
      - watch
  
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - roles
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      # The RBAC manager may grant access it does not have.
      - escalate

  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - bind

  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - "*"
  
  - apiGroups:
      - pkg.crossplane.io
    resources:
      - controllerconfigs
      - providers
    verbs:
      - create 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krateo-kube-bridge-rolebinding
  namespace: krateo-system
  labels:
    app.kubernetes.io/name: krateo-kube-bridge-manage-namespaces
    app.kubernetes.io/component: control-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krateo-manager
subjects:
  - kind: ServiceAccount
    name: krateo-kube-bridge
    namespace: krateo-system