---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krateo-kube-bridge
  namespace: krateo-system
  labels:
    app.kubernetes.io/name: krateo-kube-bridge
    app.kubernetes.io/component: control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krateo-manage-namespaces
  labels:
    app.kubernetes.io/name: krateo-manage-namespaces
    app.kubernetes.io/component: control-plane
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - serviceaccounts
    verbs:
      - create
      - get
      - delete
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krateo-kube-bridge-manage-namespaces
  namespace: krateo-system
  labels:
    app.kubernetes.io/name: krateo-kube-bridge-manage-namespaces
    app.kubernetes.io/component: control-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krateo-manage-namespaces
subjects:
  - kind: ServiceAccount
    name: krateo-kube-bridge
    namespace: krateo-system