name: release

on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to CR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: make image.build
      
      - name: Build Helm Chart
        run: make chart
      
      #- uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.HELM_CHARTS_BOT }}
          charts_dir: ./
          charts_url: https://charts.krateo.io
          owner: krateoplatformops
          repository: helm-charts
          branch: gh-pages
          linting: off
          #target_dir: kube-bridge
          #commit_username: johndoe
          #commit_email: johndoe@example.com
